apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
spec:
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: alertmanager
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-main
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30093
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: main

