apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-alertmanager
  labels:
    alertmanagerConfig: alertmanager
spec:
  route:
    groupBy: ['alertname']
    groupWait: 10s
    groupInterval: 5m
    repeatInterval: 3h
    receiver: 'webhook'
  receivers:
  - name: 'webhook'
    webhookConfigs:
    - url: 'http://example.com/'

